### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by lucyboll** [GuangyuZheng/art-transfer#1]
Hello, thanks for your work, we are implementing the code but "FileNotFoundError" occurred.
In the dataset directory, the "vec.npy" and the related .pickle files are lost, could you please send me the files? Or how can I build the file?

**Comment by GuangyuZheng** [comment]
You can take the all_train.sh as a reference. 
For the sentiment analysis task, run "python preprocess_amazon.py".
For the POS tagging task and NER task, run "python merge_data.py".

**Comment by lucyboll** [comment]
Oh, I think I know how to build the file, it's in the all_train.sh file.
I recommend adding the relevant process in the readme, thanks again.
Best regards!
